name = "SCU Rebalance"
version = 4
copyright = "Rowey"
description = "Rowey's Idea for what to do with the balance of the all the faction SCUs"
author = "Rowey"
url = ""
icon = ""
uid = "SCU-v04"
exclusive = false
ui_only = false
conflicts = {}
